---
book_repo: cloudfoundry/docs-book-cloudfoundry
cred_repo: pivotal-cf/docs-oss-site-credentials

repos:
- github_repo: cloudfoundry/docs-cloudfoundry-concepts
  directory: concepts
- github_repo: cloudfoundry/docs-dev-guide
  directory: devguide
- github_repo: cloudfoundry/docs-services
  directory: services
- github_repo: cloudfoundry/docs-deploying-cf
  directory: deploying
- github_repo: cloudfoundry/docs-bosh
  directory: bosh
- github_repo: cloudfoundry/docs-running-cf
  directory: running
- github_repo: cloudfoundry/docs-buildpacks
  directory: buildpacks

template_variables:
  app_domain: example.com
  quota_resource: quota space
  log_drain: .
  admin: your Cloud Foundry administrator
  api_endpoint: The URL of the Cloud Controller in your Cloud Foundry instance.

public_host: docs.cloudfoundry.org

