---
book_repo: cloudfoundry/docs-book-cloudfoundry
cred_repo: pivotal-cf/docs-oss-site-credentials

sections:
- repository:
    name: cloudfoundry/docs-cloudfoundry-concepts
  directory: concepts
- repository:
    name: cloudfoundry/docs-dev-guide
  directory: devguide
- repository:
    name: cloudfoundry/docs-cf-admin
  directory: adminguide
- repository:
    name: cloudfoundry/docs-services
  directory: services
- repository:
    name: cloudfoundry/docs-deploying-cf
  directory: deploying
- repository:
    name: cloudfoundry/docs-bosh
  directory: bosh
- repository:
    name: cloudfoundry/docs-running-cf
  directory: running
- repository:
    name: cloudfoundry/docs-buildpacks
  directory: buildpacks

template_variables:
  app_domain: example.com
  quota_resource: quota space
  log_drain: .
  admin: your Cloud Foundry administrator
  api_endpoint: <a href="/adminguide/api-endpoint.html">The URL of the Cloud Controller in your Cloud Foundry instance</a>

public_host: docs.cloudfoundry.org

