---
book_repo: cloudfoundry/docs-book-cloudfoundry
cred_repo: pivotal-cf/docs-oss-site-credentials

sections:
- repository:
    name: cloudfoundry/docs-cloudfoundry-concepts
  directory: concepts
- repository:
    name: cloudfoundry/docs-dev-guide
  directory: devguide
- repository:
    name: cloudfoundry/docs-cf-admin
  directory: adminguide
- repository:
    name: cloudfoundry/docs-services
  directory: services
- repository:
    name: cloudfoundry/docs-deploying-cf
  directory: deploying
- repository:
    name: cloudfoundry/docs-bosh
  directory: bosh
- repository:
    name: cloudfoundry/docs-running-cf
  directory: running
- repository:
    name: cloudfoundry/docs-buildpacks
  directory: buildpacks

template_variables:
  app_domain: example.com
  quota_resource: quota space
  external_ips: external IP addresses
  admin: your Cloud Foundry administrator
  api_endpoint: <a href="/devguide/deploy-apps/api-endpoint.html">The URL of the Cloud Controller in your Cloud Foundry instance</a>
  info_loc: In your Cloud Foundry deployment manifest
  uaa_cred: refer to the the <code>uaa scim</code> section
  GSG_intro_sentence:
  product_full: Cloud Foundry
  product_short: Cloud Foundry
  product_site: http://docs.cloudfoundry.org
  known_issues: <a href="./../../running/troubleshooting.html">Troubleshooting Cloud Foundry</a>
  dev_console_note:
  dev_console_1:
  dev_console_2:
  dev_console_3: 
  gen_GSG: 
  pws_bullet: 

public_host: docs.cloudfoundry.org


