---
book_repo: cloudfoundry/docs-book-cloudfoundry

broken_link_exclusions: iefix|arrowhead|#
repo_link_enabled: true
elastic_search: true

public_host: docs.cloudfoundry.org

sections:
- repository:
    name: cloudfoundry/docs-bosh
    ref: review
  directory: bosh
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-buildpacks
    ref: review
  directory: buildpacks
  subnav_template: cf-subnav.erb
  dependent_sections:
  - repository:
      name: cloudfoundry-samples/pong_matcher_grails
    no_docs: true
  - repository:
      name: cloudfoundry-samples/pong_matcher_groovy
    no_docs: true
  - repository:
      name: cloudfoundry-samples/pong_matcher_spring
    no_docs: true
  - repository:
      name: cloudfoundry-samples/pong_matcher_ruby
    no_docs: true
- repository:
    name: cloudfoundry/docs-cf-admin
    ref: review
  directory: adminguide
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-cf-cli
    ref: review
  directory: cf-cli
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-cloudfoundry-concepts
    ref: review
  directory: concepts
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-deploying-cf
    ref: review
  directory: deploying
  subnav_template: cf-subnav.erb
  dependent_sections:
  - repository:
      name: cloudfoundry/cf-release
    no_docs: true
- repository:
    name: cloudfoundry/docs-dev-guide
    ref: review
  directory: devguide
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-loggregator
    ref: review
  directory: loggregator
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-running-cf
    ref: review
  directory: running
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-services
    ref: review
  directory: services
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/uaa
    ref: gh-pages
  directory: api/uaa
