---
book_repo: cloudfoundry/docs-book-cloudfoundry
cred_repo: pivotal-cf/docs-oss-site-credentials

sections:
- repository:
    name: cloudfoundry/docs-cloudfoundry-concepts
  directory: concepts
- repository:
    name: cloudfoundry/docs-dev-guide
  directory: devguide
- repository:
    name: cloudfoundry/docs-cf-admin
  directory: adminguide
- repository:
    name: cloudfoundry/docs-services
  directory: services
- repository:
    name: cloudfoundry/docs-deploying-cf
  directory: deploying
- repository:
    name: cloudfoundry/docs-bosh
  directory: bosh
- repository:
    name: cloudfoundry/docs-running-cf
  directory: running
- repository:
    name: cloudfoundry/docs-buildpacks
  directory: buildpacks

template_variables:
  app_domain: example.com
  quota_resource: quota space
  external_ips: external IP addresses
  admin: your Cloud Foundry administrator
  api_endpoint: <a href="http://docs.cloudfoundry.org/devguide/deploy-apps/api-endpoint.html">the URL of the Cloud Controller in your Cloud Foundry instance</a>
  info_loc: In your Cloud Foundry deployment manifest
  uaa_cred: refer to the the <code>uaa scim</code> section
  GSG_intro_sentence:
  product_full: Cloud Foundry
  product_short: Cloud Foundry
<<<<<<< HEAD
  known_issues: <a href="http://docs.cloudfoundry.org/running/troubleshooting.html">Troubleshooting Cloud Foundry</a>
=======
  known_issues: <a href="./../../running/troubleshooting.html">Troubleshooting Cloud Foundry</a>
>>>>>>> e7c2620a75ae871ac3d3456539e7e3a00da55e6a
  dev_console_note:
  dev_console_1:
  dev_console_2: CLI
  dev_console_3:
  dev_console_4:  
  gen_GSG: 
  cli_v6: <a href="http://docs.cloudfoundry.org/devguide/installcf/whats-new-v6.html">Getting Started with cf v6</a>
  

public_host: docs.cloudfoundry.org


