---
repos:
- github_repo: cloudfoundry/docs-cloudfoundry-concepts
  directory: concepts
- github_repo: cloudfoundry/docs-dev-guide
  directory: devguide
github:
  username: <%= ENV['GITHUB_USER'] %>
  password: <%= ENV['GITHUB_PASSWORD'] %>
aws:
  access_key: <%= ENV['AWS_ACCESS_KEY'] %>
  secret_key: <%= ENV['AWS_SECRET_KEY'] %>
  green_builds_bucket: <%= ENV['AWS_GREEN_BUILDS_BUCKET'] %>
cloud_foundry:
  username: <%= ENV['PWS_USERNAME'] %>
  password: <%= ENV['PWS_PASSWORD'] %>
  staging_space: <%= ENV['PWS_STAGING_SPACE'] %>
  staging_host: <%= ENV['PWS_STAGING_HOST'] %>
  production_space:
  production_host:
  app_name: docs
  api_endpoint: https://api.run.pivotal.io
  organization: pivotal
  public_host:

